version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.3

    working_directory: /go/src/github.com/yutopp/go-rtmp

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      - run: mkdir -p $TEST_RESULTS

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

      - run: go get github.com/jstemmer/go-junit-report
      - run: go get github.com/haya14busa/goverage
      - run: go get github.com/mattn/goveralls

      - run:
          name: Install dependency packages
          command: make dep-init

      - run:
          name: Run unittests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test | tee ${TEST_RESULTS}/go-test.out

      - store_test_results:
          path: /tmp/test-results

      - run:
          name: Measure coverage
          command: goverage -coverprofile=/tmp/coverage.out ./...

      - run:
          name: Send coverage
          command: goveralls -coverprofile=/tmp/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
